---
development:
  dialect: postgres
  database: bootehng
  user: bootehng
  password: skmP8sZ8J5tnxRW8Oij6qDQBBHMEbrrI
  host: drona.db.elephantsql.com
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://bootehng:skmP8sZ8J5tnxRW8Oij6qDQBBHMEbrrI@1drona.db.elephantsql.com:5432/bootehng?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://bootehng:skmP8sZ8J5tnxRW8Oij6qDQBBHMEbrrI@1drona.db.elephantsql.com:5432/bootehng?sslmode=disable"}}
